apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Java Maven Build
on:
  push:
    branches:
      - "**"
jobs:
  build-test:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout
      - uses: docker://maven:3-eclipse-temurin-17
        name: Maven Build
        shell: sh
        run: |
          mvn clean test 
      - name: Scan with Find Security Bugs
        uses: cloudbees-io/findsecbugs-sast-scan-code@v1
        with:
          language: "LANGUAGE_JAVA"
      - uses: cloudbees-io/checkmarx
        name: Checkmarx-Scan
        with:
          serverURL: ${{ vars.CHECKMARX_SERVER_URL }}
          username: ${{ secrets.CHECKMARX_USERNAME }}
          password: ${{ secrets.CHECKMARX_PASSWORD }}
          token: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
          language: LANGUAGE_JAVA
  osv-scan:
    steps:
      - name: install
        uses: docker://owasp/sonarqube
        shell: sh
        run: |
          apk add osv-scanner
