apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Simple Java Maven Build
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      
      - name: Maven Build
        uses: docker://maven:3-eclipse-temurin-17
        shell: sh
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.token=${{secrets.RICH-SONAR-TOKEN}}\
            -Dsonar.host.url=https://sonarcloud.io\
            -Dsonar.organization=${{vars.RICH-SONAR-ORG}}\
            -Dsonar.projectKey=${{vars.RICH-SONAR-PROJECT-KEY}}  
      
      - name: Checkmarx Scan
        uses: cloudbees-io/checkmarx
        with:
          serverURL: ${{ vars.CHECKMARX_SERVER_URL }}
          username: ${{ secrets.CHECKMARX_USERNAME }}
          password: ${{ secrets.CHECKMARX_PASSWORD }}
          token: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
          language: LANGUAGE_JAVA



