apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Java Maven Build
on:
  push:
    branches:
      - "**"
jobs:
  build-test:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Maven Build
        uses: docker://maven:3-eclipse-temurin-17
        shell: sh
        run: |
          mvn clean test 
      - name: FindBugs Scan
        uses: cloudbees-io/findsecbugs-sast-scan-code
        with:
          language: Java
      - name: Checkmarx-Scan
        uses: cloudbees-io/checkmarx
        with:
          serverURL: ${{ vars.CHECKMARX_SERVER_URL }}
          username: ${{ secrets.CHECKMARX_USERNAME }}
          password: ${{ secrets.CHECKMARX_PASSWORD }}
          token: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
          language: LANGUAGE_JAVA
  osv-scan:
    steps:
      - name: install
        uses: docker://owasp/sonarqube
        shell: sh
        run: |
           apk add osv-scanner